### PR TITLE
Teacher menu

### PR DESCRIPTION
**Pull request by RobStallion**
Update clinicians view of teachers and service users when in caseload #316

### CODE REVIEW

**Comment by RobStallion** [comment]
Have had an issue trying to test the files in `apps/healthlocker/web/controllers/oxleas_adhd/caseload/*`. The tests for the files in there do not appear to be running. I have asked a question on SO [here](https://stackoverflow.com/questions/48831241/testing-phoenix-controllers-that-are-in-nested-folders) 

@nelsonic this code appears to be working when run locally but, so far, I have been unable to add tests for the new actions.

**Comment by nelsonic** [comment]
@RobStallion the code & tests in this PR look good. 👍 
I've up-voted your StackOverflow question. (_hope to get a reply ..._) ⏳ 
Will hold off merging for a bit so "Dogbert" has time to answer. 😉

**Comment by RobStallion** [comment]
@nelsonic Any news on the PR?

**Comment by nelsonic** [comment]
Hi @RobStallion, it's not a `case` of not _wanting_ to merge it.
Did you see the _reply_ on your StackOverflow question?
Worth leaving a comment on it if it is/not helpful. 😉

**Comment by RobStallion** [comment]
@nelsonic I just spotted the error. This is sort of how I felt at the time 😐+ 😄+ 😭. Have updated the tests 👍. Cannot believe that that was the error. This has been in the code since 10/5/17 🙈

**Review by nelsonic — APPROVED** [review]
@RobStallion stoked you spotted the naming issue and fixed it. 🎉 
Code looks great. thanks! :shipit:

**Pull request merged**
