### PR TITLE
insert GA tracking code

### PR DESCRIPTION
**Pull request by MollieCourtenay**
#158

### CODE REVIEW

**Comment by reddog** [comment]
@iteles Just wondering why @RobStallion's been assigned to this issue and not @SimonLab who has been assigned to all of the other PRs in this sprint.  I know there are a number of other items that @RobStallion is already working through.

**Comment by iteles** [comment]
@reddog, @RobStallion is more intimately familiar with the ins and outs of the application and as this code needs to be on every page, I was asking him to double check if anything else is required.
This is a 3 minute check that wouldn't affect the remainder of the items on the list for today.

**Comment by reddog** [comment]
@RobStallion @SimonLab Great - can this be merged now?

**Comment by RobStallion** [comment]
@reddog I was waiting for the tests to pass

**Pull request merged**
