### PR TITLE
Medication

### PR DESCRIPTION
**Pull request by katbow**
#15 adds functionality for clinicians to add & edit medication info
 #16 adds functionality for SUs to view medication notes
#85 styling for each section

### CODE REVIEW

**Comment by harrygfox** [comment]
@katbow slight issue: @medication.past_medication does not render on the `show.html.eex` view:
image

**Comment by harrygfox** [comment]
I believe styles for this have been completed 🎨 🖌

**Comment by katbow** [comment]
thanks @harrygfox, fixed my part now too! thanks for the beautiful styling ❤️

**Comment by nelsonic** [comment]
@harryfox styles looking fly! Great work!

**Pull request merged**
