### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by RobStallion**
created a copy of the `HL app` but renamed it to `app` #52

### CODE REVIEW

**Comment by nelsonic** [comment]
@RobStallion unless we are going _modularise_ HL, 
creating a _duplicate_ codebase is _probably_ not a good idea for _maintenance_ purposes ... 😕

**Comment by nelsonic** [comment]
@RobStallion call me when you're online. 👍

**Comment by reddog** [comment]
@nelsonic Great point about future maintainability. I raised a similar point during the planning session around implementing *feature switches* within a single codebase.

**Comment by RobStallion** [comment]
@nelsonic I have tried to call a couple of times but I am not getting any answer 😕

**Comment by nelsonic** [comment]
@RobStallion apologies, the network here has been poor. 📵 😞 
Please try again now if you can. thanks.

**Comment by reddog** [comment]
@nelsonic Sorry to hear that you've been having signal issues today.

@RobStallion Has this blocked you today, given that the architecture conversation was needed before continuing?

@nelsonic & @RobStallion When is the tech architecture conversation happening - I'll check my diary.

**Comment by nelsonic** [comment]
Hi @reddog, @RobStallion and I had a _telephone_ conversation this evening regarding what to do.
We will be _splitting_ out the ePJS-related code into an "umbrella" and analysing the _difference_ between the `oxleas` and (SLaM) `healthlocker` instances of the app to figure out if there are any _other_ "Umbrella" apps we can isolate.

If you are _unfamiliar_ with Umbrella apps, they are simply a "micro-service" that is run in a "supervision tree" by the main app. (_so they are run on the same server/VM and do not add to deployment complexity_)

I'd recommend watching this presentation to gain further understanding:
[image](https://youtu.be/1ocF_9Nc0ik)
https://youtu.be/1ocF_9Nc0ik

Our _plan_ is to _minimise_ the amount of code "duplication" and use configuration files for deployment as much as possible rather than customising the code directly. 
Any oxleas-specific customisation will be done in an `oxleas` umbrella app.

@RobStallion will be expanding on this _plan_ with _several_ `technical` issues 
which will be adding lost of detail so hopefully _anyone_ else can follow and reproduce.

**Comment by nelsonic** [comment]
Keeping branch in repo till Umbrella App is done. 👍

**Comment by RobStallion** [comment]
Yeah that's the plan. Just thought that I may as well close the PR 👍

**Pull request closed without merging**
